from typing import Final


TOPICS: Final = (
    "introductions",
    "family",
    "daily routine",
    "hobbies",
    "pets",
    "home",
    "weekends",
    "holidays",
    "clothing",
    "shopping",
    "birthdays",
    "personal preferences",
    "morning activities",
    "evening activities",
    "household chores",
    "neighborhoods",
    "free time",
    "school",
    "work",
    "friends",
    "greetings",
    "saying goodbye",
    "compliments",
    "dating",
    "meeting new people",
    "visiting others",
    "offering help",
    "apologizing",
    "thanking",
    "giving gifts",
    "receiving gifts",
    "parties",
    "phone calls",
    "social media",
    "invitations",
    "emotions",
    "humor",
    "small talk",
    "restaurants",
    "ordering food",
    "traditional food",
    "cooking",
    "grocery shopping",
    "mealtimes",
    "eating habits",
    "drinks",
    "snacks",
    "dietary needs",
    "describing flavors",
    "kitchens",
    "table manners",
    "rooms in a house",
    "furniture",
    "describing places",
    "moving",
    "appliances",
    "safety at home",
    "housing",
    "decorating",
    "repairs",
    "body parts",
    "illness",
    "visiting the doctor",
    "medicine",
    "dentist visits",
    "healthy habits",
    "exercise",
    "mental health",
    "first aid",
    "emergencies",
    "taxis",
    "public transportation",
    "hotels",
    "airports",
    "asking directions",
    "road signs",
    "driving",
    "renting vehicles",
    "traveling",
    "landmarks",
    "packing",
    "culture shock",
    "travel documents",
    "travel tips",
    "weather",
    "seasons",
    "natural disasters",
    "beaches",
    "camping",
    "animals",
    "parks",
    "forests",
    "environment",
    "jobs",
    "professions",
    "job tasks",
    "job applications",
    "job interviews",
    "colleagues",
    "schedules",
    "studying",
    "school subjects",
    "teachers",
    "tests",
    "classmates",
    "online classes",
    "career plans",
    "phones",
    "computers",
    "apps",
    "the internet",
    "online shopping",
    "video games",
    "email",
    "taking photos",
    "watching videos",
    "navigation tools",
    "movies",
    "cinemas",
    "music",
    "concerts",
    "television",
    "books",
    "theater",
    "museums",
    "festivals",
    "podcasts",
    "asking questions",
    "giving answers",
    "making suggestions",
    "agreeing",
    "disagreeing",
    "giving opinions",
    "descriptions",
    "giving directions",
    "asking for help",
    "clarifying",
    "vocabulary learning",
    "correcting mistakes",
    "common expressions",
    "slang",
    "idioms",
    "pronunciation practice",
    "numbers",
    "telling time",
    "days of the week",
    "months",
    "seasonal changes",
    "time expressions",
    "ages",
    "dates",
    "appointments",
    "time zones",
    "prices",
    "paying",
    "credit cards",
    "budgets",
    "saving money",
    "banks",
    "currency exchange",
    "splitting bills",
    "financial goals",
    "online banking",
    "customs",
    "manners",
    "celebrations",
    "religion",
    "traditions",
    "superstitions",
    "language learning",
    "stereotypes",
    "diversity",
    "international experiences",
    "laws",
    "rules",
    "police",
    "driver's licenses",
    "voting",
    "immigration",
    "public services",
    "taxes",
    "housing contracts",
    "civil status",
    "calling emergency services",
    "fire safety",
    "lost items",
    "accidents",
    "theft",
    "hospital visits",
    "safety tips",
    "natural disasters",
    "identification",
    "emergency contacts",
)
